style css
Scheleto/landing pull request #3
Opened 2024-01-13 00:43 UTC by Scheleto

2024-01-13 00:45 UTC, patric-vinicios commented on index.html
>               <h1>Markenting</h1>
Acho que aqui deveria ser "Marketing"

2024-01-13 00:46 UTC, patric-vinicios commented on styles/style.css
> +}
Dentro dessa estilização do `body` deveria estar indentado, ou seja, deveria ter uma espaço

2024-01-13 00:47 UTC, patric-vinicios commented on styles/style.css
> +}
Aqui deveria ter uma indentação também

2024-01-13 00:48 UTC, patric-vinicios requested changes
Rever erros gramaticais e de indentação.

2024-01-13 00:55 UTC, Scheleto commented on index.html
>               <h1>Markenting</h1>
feito.

2024-01-13 00:58 UTC, Scheleto commented on styles/style.css
> +}
feito.

2024-01-13 00:59 UTC, Scheleto commented on styles/style.css
> +}
feito.

2024-01-13 00:59 UTC, Scheleto commented on styles/style.css
> +}
feito

2024-01-17 22:32 UTC, patric-vinicios approved these changes

2024-01-17 22:34 UTC, merged